[project]
name = "ghapp-weebhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "httpx>=0.28.1",
    "jwt>=1.3.1",
    "uuid>=1.30",
]
